CREATE TABLE Professor (
	SSN INT NOT NULL,
	Pname VARCHAR(100) NOT NULL,
	Ptitle VARCHAR(100) NOT NULL,
	Psex CHAR(1) NOT NULL,
	Degree VARCHAR(64) NOT NULL,
	Salary INT NOT NULL,
	Area_code MEDIUMINT NOT NULL,
	Tel7Digit MEDIUMINT NOT NULL,
	Street VARCHAR(96) NOT NULL,
	City VARCHAR(36) NOT NULL,
	State CHAR(2) NOT NULL,
	ZIP MEDIUMINT NOT NULL,
	
	PRIMARY KEY (SSN)
);


CREATE TABLE Department(
	Dep_ID INT(5) NOT NULL AUTO_INCREMENT,
	Dep_Name VARCHAR(32) NOT NULL,
	Dep_TelNum BIGINT NOT NULL,
	Office_location VARCHAR(10) NOT NULL,
	ChairSSN INT NOT NULL,
	
	PRIMARY KEY (Dep_ID),
	FOREIGN KEY (ChairSSN) REFERENCES Professor(SSN)
);

CREATE TABLE Course (
	Course_ID CHAR(9) NOT NULL,
	Ctitle VARCHAR(32) NOT NULL,
	Units TINYINT NOT NULL,
	TextbookISBN13 CHAR(13),
	Dep_ID INT(5) NOT NULL,
	
	PRIMARY KEY (Course_ID),
	FOREIGN KEY (Dep_ID) REFERENCES Department(Dep_ID)
);

CREATE TABLE Section (
	Section_number MEDIUMINT NOT NULL,
	Course_ID CHAR(9) NOT NULL,
	Classroom VARCHAR(32) NOT NULL,
	No_seats TINYINT NOT NULL,
	Begin_time TIME NOT NULL,
	End_time TIME NOT NULL,
	P_SSN INT NOT NULL,
	
	PRIMARY KEY (Section_number),
	FOREIGN KEY (Course_ID) REFERENCES Course(Course_ID),
	FOREIGN KEY (P_SSN) REFERENCES Professor(SSN)
);

CREATE TABLE Student (
	CWID INT NOT NULL,
	Fname VARCHAR(50) NOT NULL,
	Lname VARCHAR(50) NOT NULL,
	S_TelNum BIGINT(10) NOT NULL,
	S_Address VARCHAR(256) NOT NULL,
	Major_DepID INT(5) NOT NULL,
	
	PRIMARY KEY (CWID),
	FOREIGN KEY (Major_DepID) REFERENCES Department(Dep_ID)
);


CREATE TABLE Minor (
	CWID INT NOT NULL,
	Dep_ID INT(5) NOT NULL,
	
	FOREIGN KEY (CWID) REFERENCES Student(CWID),
	FOREIGN KEY (Dep_ID) REFERENCES Department(Dep_ID)
);

CREATE TABLE Enrollment (
	CWID INT NOT NULL,
	Section_number MEDIUMINT NOT NULL,
	Grade CHAR(2),
	
	FOREIGN KEY (CWID) REFERENCES Student(CWID),
	FOREIGN KEY (Section_number) REFERENCES Section(Section_number)
);

CREATE TABLE Prerequisite (
	Course_ID CHAR(9) NOT NULL,
	Prerequisite_ID CHAR(9) NOT NULL,
	
	FOREIGN KEY (Course_ID) REFERENCES Course(Course_ID),
	FOREIGN KEY (Prerequisite_ID) REFERENCES Course(Course_ID)
);

CREATE TABLE Meeting (
	Course_ID CHAR(9) NOT NULL,
	Section_number MEDIUMINT NOT NULL,
	Day_no TINYINT NOT NULL, 
	
	FOREIGN KEY (Course_ID) REFERENCES Course(Course_ID),
	FOREIGN KEY (Section_number) REFERENCES Section(Section_number)
);